export const REGISTRO_EXITOSO = ' REGISTRO_EXITOSO';
export const REGISTRO_ERROR= ' REGISTRO_ERROR';
export const LIMPIAR_ALERTAS = ' LIMPIAR_ALERTAS';


export const USUARIO_AUTENTICADO = ' USUARIO_AUTENTICADO';